### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/HoochiePapa#1]
this addon randomizes the queue of new cards between decks? Does it work with Anki 2.1's V2 enabled?

**Comment by cjdduarte** [comment]
What about learning cards? I use step (25 1440). Are the learning cards the other day (1440) also randomized?

**Comment by lovac42** [comment]
Learning cards are time based.

**Comment by cjdduarte** [comment]
Thank you for the explanation
