### ISSUE TITLE
Strange add-on interaction

### ISSUE THREAD

**Issue by Arthur-Milchior** [lovac42/HoochiePapa#10]
Hi,

I've just received a bug report. https://github.com/Arthur-Milchior/anki-resize-image/issues/2
It seems that when the user has both my add-on and yours enabled, and nothing else, images get broken.
It's a really strange one, and I'd like to know whether you have any idea about what may be going on. 
My intuition tells me that there is a mistake in the bug report. After all, your add-on does not deal with images at all if I understand the documentation and the code. 
But in case I'm wrong, I ask for your feedback, do you have any idea what may be going on ?

**Comment by lovac42** [comment]
That would be strange as the two addons don't patch the same part of Anki, Qt, or js. And from the new user comment added an hour ago, your problem doesn't seem related to addon conflicts.

>I ask for your feedback, do you have any idea what may be going on ?

IIRC, and I could be wrong, it's possible that beautifulsoup or Qt is stripping image styles on windows when the note is saved or loaded. Have you confirmed that the saved note is the same as you expected? Anki does this in old versions as well and it's always a PITA to deal with. GL

**Comment by Arthur-Milchior** [comment]
Sorry for the message; I guess I should have waited more. It has been confirmed that actually your add-on was not related at all. And not some strange interaction I could not imagine (which, in Python, sometime occurs)
