### ISSUE TITLE
Why does he not select cards from the fifth subdeck?

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/HoochiePapa#5]
I'm testing a simple randomness between 5 subdecks with their 3 addons ("Papa", "mama" and "Baby")

I created the enclosed structure with 5 subdecks to analyze the probability of the **FIRST** card to appear and from which deck.

For the **FIRST** card, cards of the fifth subdeck (51, 52, 53, 54 or 55) are **never selected.**
Because?

[coleção-2019-01-25@09-36-48.zip](https://github.com/lovac42/HoochiePapa/files/2795872/colecao-2019-01-25%4009-36-48.zip)

**Comment by cjdduarte** [comment]
Note that he never selects cards from the fifth deck

![example](https://user-images.githubusercontent.com/42243532/51743993-912e9880-2085-11e9-9035-47f3d4f1f0e7.gif)

**Comment by lovac42** [comment]
thanks, deleted line 79 and fixed the issue. It was added for performance.

**Comment by cjdduarte** [comment]
Thank you. It worked.
