### ISSUE TITLE
Update to 2.1.20

### ISSUE THREAD

**Issue by lovac42** [lovac42/HoochiePapa#9]
Sync modules has been moved.

**Comment by ArtappsLaurens** [comment]
Are there any plans of implementing this soon? Keep up the good work

**Comment by lovac42** [comment]
Prob just a false alarm for papa and baby. Hadn't run into any issues.

**Comment by ArtappsLaurens** [comment]
Could be me, but I believe sort NewQ by Due (desc) is not working for parent decks and thought this might be related

**Comment by lovac42** [comment]
@ArtappsLaurens: I have added some tests to this addon in the recent update. If you download the latest version, go to configs, turn on tests for sorting, then go to preferences and toggle the hoochie settings, it should tell you if it's tested correctly.

**Comment by ArtappsLaurens** [comment]
@lovac42 I tried that - it says there are not enough cards in the default deck. I'm guessing the tests only work on the deck that's named 'Default'?

**Comment by lovac42** [comment]
Yeah, unless you renamed it. It would be the first provided deck on a new profile. Just create a test profile and import some shared decks for testing.
